import { z } from 'zod';
export const briefSchema=z.object({name:z.string().trim().min(2).max(100),category:z.string().min(2).max(100),offer:z.string().trim().min(5).max(1500),audience:z.string().min(2).max(300),location:z.string().min(2).max(150),goal:z.string().min(2).max(200),website:z.string().max(400).refine(v=>!v||/^https?:\/\//i.test(v),'Use a full website address beginning with https://'),start:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),budget:z.number().int().min(0).max(10000000),minutes:z.number().int().min(5).max(240),video:z.boolean(),language:z.enum(['English','Hindi','English + Hindi']),color:z.string().regex(/^#[0-9a-f]{6}$/i),demo:z.boolean()});
export type Brief=z.infer<typeof briefSchema>;
export const postSchema=z.object({id:z.string().max(100),day:z.number().int().min(0).max(6),channel:z.enum(['Instagram','WhatsApp']),title:z.string().min(1).max(120),copy:z.string().min(1).max(2500),cta:z.string().min(1).max(200),creative:z.string().min(1).max(1200),script:z.string().max(1200),format:z.enum(['Photo','Text','Video']),minutes:z.number().int().min(1).max(240),spend:z.number().int().min(0).max(10000000),approved:z.boolean()});
export type Post=z.infer<typeof postSchema>;
export const researchSchema=z.object({text:z.string().max(20000),sources:z.array(z.object({title:z.string().max(500),url:z.string().url().max(2000).refine(v=>/^https?:\/\//.test(v),'Source URLs must use HTTP or HTTPS')})).max(30),retrievedAt:z.string().max(50)});
export type Research=z.infer<typeof researchSchema>;
export const campaignSchema=z.object({id:z.string().uuid(),title:z.string().min(1).max(120),brief:briefSchema,posts:z.array(postSchema).max(30),research:researchSchema.nullable(),mode:z.enum(['template','ai']),version:z.number().int().min(0),updatedAt:z.string().max(50)}).superRefine((c,ctx)=>{if(new Set(c.posts.map(p=>p.id)).size!==c.posts.length)ctx.addIssue({code:'custom',message:'Post identifiers must be unique'});});
export type Campaign=z.infer<typeof campaignSchema>;
export function initialBrief():Brief {return {name:'The Sunday Bakery',category:'Bakery & food',offer:'Handmade cupcake boxes for celebrations, gifts, and a little weekend indulgence. Weekend preorders available.',audience:'Nearby families, friends, and office teams',location:'Bengaluru, India',goal:'Encourage weekend preorders',website:'',start:new Date().toISOString().slice(0,10),budget:1000,minutes:20,video:false,language:'English',color:'#4935e8',demo:true};}
export function dayDate(start:string,day:number){const d=new Date(start+'T12:00:00');d.setDate(d.getDate()+day);return d.toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short'});}
export function templatePosts(b:Brief):Post[]{const titles=['Meet the business','A closer look','Start a conversation','Behind the offer','Answer a question','Make your plans','Stay in touch'];const hi=['हमसे मिलिए','हमारी पेशकश','बात शुरू करें','पर्दे के पीछे','आपके सवाल','अपनी योजना बनाएं','जुड़े रहें'];return titles.map((title,day)=>{const channel=day%2===0?'Instagram':'WhatsApp';const eng=`${b.name}, ${b.location}. ${b.offer}\n\n${['Discover what we have for you.','Take a closer look at our offering.','Have a question? We’re happy to help.','Here is a little more about what we do.','Tell us what you would like to know.','Planning ahead? Ask us about availability.','Thank you for being part of our community.'][day]}`;const hindi=`${b.name}, ${b.location}\n\n${b.offer}\n\nअधिक जानकारी के लिए हमें संदेश भेजें।`;return {id:crypto.randomUUID(),day,channel,title:b.language==='Hindi'?hi[day]:title,copy:b.language==='English'?eng:b.language==='Hindi'?hindi:eng+'\n\nअधिक जानकारी के लिए हमें संदेश भेजें।',cta:b.language==='English'?'Message us to learn more':'जानकारी के लिए संदेश भेजें',creative:channel==='Instagram'?`Use an existing, accurate product or service photo. Add the headline and ${b.name}. Keep text large and show the offer clearly.`:'Use a short, personal text message for customers who opted in. Add an easy way to stop receiving updates.',script:'',format:channel==='WhatsApp'?'Text':(b.video&&day===3?'Video':'Photo'),minutes:Math.min(b.minutes,channel==='WhatsApp'?5:15),spend:0,approved:false};});}
export function adaptPosts(posts:Post[],minutes:number,video:boolean){return posts.map(p=>p.approved?p:{...p,minutes:Math.min(p.minutes,minutes),format:!video&&p.format==='Video'?'Photo' as const:p.format,script:!video&&p.format==='Video'?'':p.script,creative:!video&&p.format==='Video'?'Use an existing product or service photo with the same message. No video recording needed.':p.minutes>minutes?'Reuse an existing approved photo or text layout. Keep preparation within the new time limit.':p.creative});}
export function constraintErrors(posts:Post[],b:Brief){const errs:string[]=[];if(posts.reduce((s,p)=>s+p.spend,0)>b.budget)errs.push('Planned spending exceeds the campaign budget.');for(let day=0;day<7;day++){if(posts.filter(p=>p.day===day).reduce((s,p)=>s+p.minutes,0)>b.minutes)errs.push(`Day ${day+1} exceeds your available time.`);}if(!b.video&&posts.some(p=>p.format==='Video'))errs.push('A video is planned, but video production is unavailable.');return errs;}
export const planJsonSchema={type:'object',additionalProperties:false,properties:{posts:{type:'array',minItems:7,maxItems:7,items:{type:'object',additionalProperties:false,properties:{day:{type:'integer',minimum:0,maximum:6},channel:{type:'string',enum:['Instagram','WhatsApp']},title:{type:'string'},copy:{type:'string'},cta:{type:'string'},creative:{type:'string'},script:{type:'string'},format:{type:'string',enum:['Photo','Text','Video']},minutes:{type:'integer',minimum:1},spend:{type:'integer',minimum:0}},required:['day','channel','title','copy','cta','creative','script','format','minutes','spend']}}},required:['posts']};

export function claimWarnings(post:Post):string[]{const text=[post.title,post.copy,post.cta,post.script,post.creative].join(' ');const warnings:string[]=[];if(/last chance|limited (stock|time)|only \d+ left|ends (today|tonight)|final (chance|call)|अंतिम मौका/i.test(text))warnings.push('Confirm any deadline or scarcity claim with the business.');if(/thank you.*(ordered|preordered|purchased)|customers love|best.?sell|rated|testimonial|लोगों की पसंद/i.test(text))warnings.push('Confirm statements about past orders, reviews, or customer popularity.');if(/guarantee|number one|#1|\d+%|₹\s*\d|\bRs\.?\s*\d|सबसे अच्छा/i.test(text))warnings.push('Verify numerical, price, discount, or superiority claims.');if(/tap here|click here|link in bio/i.test(text))warnings.push('Make sure the promised order link or profile link is available.');return warnings;}
export function contrastText(hex:string){const rgb=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);const luminance=rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;return luminance>.179?'#141c31':'#ffffff';}
