import {ZodError} from 'zod';
import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export async function owner(){const u=await getChatGPTUser();if(!u)throw new HttpError(401,'Sign in to save and manage your campaigns.');return u.userId;}
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export function database(){if(!env.DB)throw new HttpError(503,'Campaign storage is unavailable. Your changes remain on this screen; please try saving again.');return env.DB;}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new HttpError(403,'This request must come from your campaign workspace.');}
export async function body(req:Request){const raw=await req.text();if(raw.length>150000)throw new HttpError(413,'This campaign is too large. Please shorten the content.');try{return JSON.parse(raw)}catch{throw new HttpError(400,'The request could not be read.');}}
export function failure(e:unknown){if(e instanceof ZodError)return Response.json({error:'Please check the supplied details: '+e.issues[0].message},{status:400});if(e instanceof HttpError)return Response.json({error:e.message},{status:e.status});console.error('Campaign request failed',e instanceof Error?e.message:'Unknown error');return Response.json({error:'We could not complete that step. Your current work is unchanged. Please try again.'},{status:500});}
export function runtime(){return env as typeof env & {OPENAI_API_KEY?:string;OPENAI_MODEL?:string}}
export async function reserveAI(user:string){const key=user+':'+new Date().toISOString().slice(0,10);const result=await database().prepare('INSERT INTO usage (id,count) VALUES (?,1) ON CONFLICT(id) DO UPDATE SET count=count+1 WHERE count<20 RETURNING count').bind(key).first();if(!result)throw new HttpError(429,'The daily limit of 20 AI requests has been reached. You can still edit and export campaigns.');}
export async function responseRequest(payload:Record<string,unknown>){const config=runtime();if(!config.OPENAI_API_KEY)throw new HttpError(503,'OpenAI is not connected yet. You can use the clearly labelled starter template meanwhile.');const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${config.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:config.OPENAI_MODEL||'gpt-4.1-mini',store:false,...payload}),signal:AbortSignal.timeout(90000)});if(!r.ok)throw new HttpError(502,r.status===429?'OpenAI is currently rate limited or out of quota. Please check the connected account and try again.':'OpenAI could not complete this request. Please check the account connection and try again.');return r.json() as Promise<any>;}
export function outputText(data:any){return (data.output||[]).filter((o:any)=>o.type==='message').flatMap((o:any)=>o.content||[]).filter((c:any)=>c.type==='output_text').map((c:any)=>c.text).join('\n');}
